gitConfig:
  alias.st: status
tasks:
  - name: Setup fnm (Fast node manager)
    before: curl -fsSL https://fnm.vercel.app/install | bash
    init: |
      source /home/gitpod/.bashrc
      fnm install --latest
  - name: Global dependencies
    before: ./setup.sh
  - name: Setup slides
    init: cd slides && npm install
  - name: Setup catalyst
    init: npm install
  - name: Start docker service
    command: "docker run -d -p 8080:8080 -e PLANTUML_LIMIT_SIZE=15000 plantuml/plantuml-server:jetty-v1.2023.1"
    openMode: tab-after
  - name: Start slides service
    command: cd slides && npm run dev
    openMode: tab-after
  - name: Start typecript service
    command: npm run dev
    openMode: tab-after

vscode:
  extensions:
    - jebbs.plantuml
    - redhat.vscode-xml
    - jock.svg
    - DavidAnson.vscode-markdownlint
    - hediet.vscode-drawio
    - usernamehw.errorlens
    - Codeium.codeium
