@startuml ERP Integration Overview
!include ./C4_Component.puml

scale 1.0
title Input diagram

System(AX, "label", "technology", "description tytter") {
    Container(AIF, "Application Integration Framework", "ERP service", "This is also awesome", $tags=tytter) {
        Component(END, "API endpoint", "ERP service", "This is also awesome", $tags=tytter)
    }
}
System(AX2, "Microsoft Dynamics AX", "ERP system", "Description tytter") {
    Container(AIF2, "Application Integration Framework", "ERP service", "This is also awesome", $tags=tytter) {
        Component(END2, "API endpoint", "ERP service", "This is also awesome", $tags=tytter)
    }
}

System(AX3, "Microsoft Dynamics AX", "ERP system", "This is awesome") {
    Component(END3, "API endpoint", "ERP service", "This is also awesome", $tags=tytter)
}

Rel(END, END2, "Label Relation 1", "Technology relation 1")

Rel(AIF, END3, "Label Relation 2", "Technology relation 2")



LAYOUT_TOP_DOWN()
SHOW_LEGEND()
@enduml
