export enum EntityType {
    Person = 'Person',
    Person_Ext = 'Person_Ext',
    System = 'System',
    SystemDb = 'SystemDb',
    SystemQueue = 'SystemQueue',
    System_Ext = 'System_Ext',
    SystemDb_Ext = 'SystemDb_Ext',
    SystemQueue_Ext = 'SystemQueue_Ext',
    Container = 'Container',
    ContainerDb = 'ContainerDb',
    ContainerQueue = 'ContainerQueue',
    Container_Ext = 'Container_Ext',
    ContainerDb_Ext = 'ContainerDb_Ext',
    ContainerQueue_Ext = 'ContainerQueue_Ext',
    Component = 'Component',
    ComponentDb = 'ComponentDb',
    ComponentQueue = 'ComponentQueue',
    Component_Ext = 'Component_Ext',
    ComponentDb_Ext = 'ComponentDb_Ext',
    ComponentQueue_Ext = 'ComponentQueue_Ext',
}